"use client";

import { useState, useEffect, useCallback } from 'react';
import Header from '@/components/Header';
import BottomNav from '@/components/BottomNav';
import { BarChart2, Users, TrendingDown, TrendingUp, FileDown } from 'lucide-react';
import { getMyPendingGiven, getAllTransactions, Transaction, ME } from '@/services/payattuService';

// ── Skeleton components ────────────────────────────────────────────────────────
function SkeletonStatCard() {
    return (
        <div style={{ flex: 1, minWidth: '140px', background: '#F3F4F6', borderRadius: '0.75rem', padding: '1rem' }}>
            <div className="skeleton skeleton-text short" style={{ marginBottom: '0.5rem' }} />
            <div className="skeleton skeleton-text wide" />
        </div>
    );
}

function SkeletonMemberRow() {
    return (
        <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '0.875rem 1.25rem', background: 'white', borderRadius: '0.75rem',
            border: '1px solid var(--border)', marginBottom: '0.75rem', boxShadow: 'var(--shadow-sm)'
        }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                <div className="skeleton skeleton-circle" style={{ width: 38, height: 38, borderRadius: '50%' }} />
                <div className="skeleton skeleton-text wide" />
            </div>
            <div style={{ width: 70, textAlign: 'right' }}>
                <div className="skeleton skeleton-text full" />
                <div className="skeleton skeleton-text short" style={{ marginLeft: 'auto', marginTop: 4 }} />
            </div>
        </div>
    );
}

// ── PDF generator ──────────────────────────────────────────────────────────────
function generateReceivablePdf(
    groups: { memberId: string; memberName: string; totalGiven: number }[],
    total: number
) {
    const myName = localStorage.getItem('payattu_username') || 'Me';
    const today = new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' });
    const sorted = [...groups].sort((a, b) => b.totalGiven - a.totalGiven);

    const rows = sorted.map((g, i) => `
        <tr>
            <td>${i + 1}</td>
            <td>${g.memberName}</td>
            <td class="amount">₹${g.totalGiven.toLocaleString('en-IN')}</td>
        </tr>`).join('');

    const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<title>Receivable Report</title>
<style>
  body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #111; }
  h1 { font-size: 28px; font-weight: 800; color: #4F46E5; margin: 0 0 4px; }
  .sub { font-size: 13px; color: #6B7280; margin-bottom: 28px; }
  .meta { display: flex; gap: 40px; margin-bottom: 28px; }
  .meta div { font-size: 13px; }
  .meta div span { font-weight: 700; color: #111; display: block; font-size: 15px; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
  th { background: #4F46E5; color: white; padding: 10px 14px; text-align: left; font-size: 13px; }
  td { padding: 10px 14px; border-bottom: 1px solid #E5E7EB; font-size: 14px; }
  tr:last-child td { border-bottom: none; }
  .amount { text-align: right; font-weight: 600; }
  th:last-child { text-align: right; }
  .total-row td { font-weight: 800; font-size: 15px; background: #F5F3FF; color: #4F46E5; }
  .footer { font-size: 11px; color: #9CA3AF; border-top: 1px solid #E5E7EB; padding-top: 12px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<h1>Receivable Report</h1>
<p class="sub">Pending amounts owed to you from Payattu contributions</p>
<div class="meta">
  <div>Date<span>${today}</span></div>
  <div>Prepared by<span>${myName}</span></div>
  <div>Members<span>${groups.length}</span></div>
</div>
<table>
  <thead><tr><th>#</th><th>Member</th><th style="text-align:right">Amount Owed</th></tr></thead>
  <tbody>
    ${rows}
    <tr class="total-row">
      <td colspan="2">Total Receivable</td>
      <td class="amount">₹${total.toLocaleString('en-IN')}</td>
    </tr>
  </tbody>
</table>
<p class="footer">Generated by PayattuBook · ${today}</p>
<script>window.onload = () => { window.print(); }<\/script>
</body>
</html>`;

    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(html);
    win.document.close();
}

export default function AnalyticsPage() {
    const [pendingGroups, setPendingGroups] = useState<{ memberId: string; memberName: string; totalGiven: number }[]>([]);
    const [allTxs, setAllTxs] = useState<Transaction[]>([]);
    const [loading, setLoading] = useState(true);

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const [groups, txs] = await Promise.all([getMyPendingGiven(), getAllTransactions()]);
            setPendingGroups(groups);
            setAllTxs(txs);
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => { load(); }, [load]);

    const totalPendingGiven = pendingGroups.reduce((s, g) => s + g.totalGiven, 0);
    const totalReceived = allTxs.filter(t => t.receiverId === ME).reduce((s, t) => s + t.amount, 0);

    return (
        <div className="page-container">
            <Header title="Analytics" />
            <main style={{ flex: 1, padding: '1.25rem', overflowY: 'auto' }}>

                {/* PDF Export button */}
                {!loading && pendingGroups.length > 0 && (
                    <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: '1rem' }}>
                        <button
                            onClick={() => generateReceivablePdf(pendingGroups, totalPendingGiven)}
                            style={{
                                display: 'flex', alignItems: 'center', gap: '0.4rem',
                                background: '#4F46E5', color: 'white',
                                padding: '0.55rem 1rem', borderRadius: '0.5rem',
                                fontSize: '0.82rem', fontWeight: 600,
                                boxShadow: '0 2px 8px rgba(79,70,229,0.3)'
                            }}
                        >
                            <FileDown size={16} /> Export PDF
                        </button>
                    </div>
                )}

                {/* Summary Cards */}
                <div style={{ display: 'flex', gap: '0.75rem', marginBottom: '1.5rem', flexWrap: 'wrap' }}>
                    {loading ? (
                        <>
                            <SkeletonStatCard />
                            <SkeletonStatCard />
                        </>
                    ) : (
                        <>
                            <StatCard
                                icon={<TrendingDown size={18} color="#F59E0B" />}
                                label="Total Given (Pending)"
                                value={`₹${totalPendingGiven.toLocaleString('en-IN')}`}
                                accent="#FEF3C7"
                            />
                            <StatCard
                                icon={<TrendingUp size={18} color="#22C55E" />}
                                label="Total Received Back"
                                value={`₹${totalReceived.toLocaleString('en-IN')}`}
                                accent="#DCFCE7"
                            />
                        </>
                    )}
                </div>

                {/* Per-member breakdown */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '1rem' }}>
                    <div className="icon-circle" style={{ backgroundColor: 'var(--primary)', width: 32, height: 32 }}>
                        <Users size={16} color="white" />
                    </div>
                    <h2 style={{ fontSize: '0.95rem', fontWeight: 600 }}>Pending by Member</h2>
                </div>

                {loading ? (
                    <>
                        <SkeletonMemberRow />
                        <SkeletonMemberRow />
                        <SkeletonMemberRow />
                    </>
                ) : pendingGroups.length === 0 ? (
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '2rem 0', color: '#9CA3AF', gap: '0.75rem' }}>
                        <BarChart2 size={48} color="#D1D5DB" />
                        <p style={{ fontSize: '0.875rem' }}>No pending amounts</p>
                    </div>
                ) : (
                    pendingGroups
                        .sort((a, b) => b.totalGiven - a.totalGiven)
                        .map(g => (
                            <div key={g.memberId} style={{
                                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                padding: '0.875rem 1.25rem', background: 'white', borderRadius: '0.75rem',
                                border: '1px solid var(--border)', marginBottom: '0.75rem',
                                boxShadow: 'var(--shadow-sm)'
                            }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                                    <div className="avatar-circle" style={{ width: 38, height: 38, flexShrink: 0 }} />
                                    <span style={{ fontSize: '0.9rem', fontWeight: 600 }}>{g.memberName}</span>
                                </div>
                                <div style={{ textAlign: 'right' }}>
                                    <p style={{ fontSize: '0.95rem', fontWeight: 700, color: '#F59E0B' }}>
                                        ₹{g.totalGiven.toLocaleString('en-IN')}
                                    </p>
                                    <p style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>pending return</p>
                                </div>
                            </div>
                        ))
                )}

                <div style={{ height: '100px' }} />
            </main>
            <BottomNav />
        </div>
    );
}

function StatCard({ icon, label, value, accent }: { icon: React.ReactNode; label: string; value: string; accent: string }) {
    return (
        <div style={{
            flex: 1, minWidth: '140px', background: accent, borderRadius: '0.75rem',
            padding: '1rem', display: 'flex', flexDirection: 'column', gap: '0.4rem'
        }}>
            {icon}
            <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: 500 }}>{label}</p>
            <p style={{ fontSize: '1.1rem', fontWeight: 700, color: 'var(--text-main)' }}>{value}</p>
        </div>
    );
}
